import { PlayerAction, ServerPlayerActionType } from './objects/enum';

export const ServerToClientActionMap: Partial<
  Record<ServerPlayerActionType, PlayerAction>
> = {
  [ServerPlayerActionType.Attack1]: PlayerAction.PLAYER_ATTACK_FIST,
  [ServerPlayerActionType.Attack2]: PlayerAction.PLAYER_ATTACK_FIST,
  [ServerPlayerActionType.Stand1]: PlayerAction.PLAYER_STOP_MALE,
  [ServerPlayerActionType.Stand2]: PlayerAction.PLAYER_STOP_MALE,
  [ServerPlayerActionType.Move1]: PlayerAction.PLAYER_WALK_MALE,
  [ServerPlayerActionType.Move2]: PlayerAction.PLAYER_WALK_MALE,
  [ServerPlayerActionType.Damage1]: PlayerAction.PLAYER_SHOCK,
  [ServerPlayerActionType.Die1]: PlayerAction.PLAYER_DIE1,
  [ServerPlayerActionType.Sit]: PlayerAction.PLAYER_SIT1,
  [ServerPlayerActionType.Healing]: PlayerAction.PLAYER_HEALING1,
  [ServerPlayerActionType.Pose]: PlayerAction.PLAYER_RESPECT1,
  [ServerPlayerActionType.Greeting]: PlayerAction.PLAYER_GREETING1,
  [ServerPlayerActionType.Goodbye]: PlayerAction.PLAYER_GOODBYE1,
  [ServerPlayerActionType.Clap]: PlayerAction.PLAYER_CLAP1,
  [ServerPlayerActionType.Gesture]: PlayerAction.PLAYER_GESTURE1,
  [ServerPlayerActionType.Direction]: PlayerAction.PLAYER_DIRECTION1,
  [ServerPlayerActionType.Unknown]: PlayerAction.PLAYER_UNKNOWN1,
  [ServerPlayerActionType.Cheer]: PlayerAction.PLAYER_CHEER1,
  [ServerPlayerActionType.See]: PlayerAction.PLAYER_SEE1,
  [ServerPlayerActionType.Win]: PlayerAction.PLAYER_WIN1,
  [ServerPlayerActionType.Smile]: PlayerAction.PLAYER_SMILE1,
  [ServerPlayerActionType.Sleep]: PlayerAction.PLAYER_SLEEP1,
  [ServerPlayerActionType.Cold]: PlayerAction.PLAYER_COLD1,
  [ServerPlayerActionType.Again]: PlayerAction.PLAYER_AGAIN1,
  [ServerPlayerActionType.Respect]: PlayerAction.PLAYER_RESPECT1,
  [ServerPlayerActionType.Salute]: PlayerAction.PLAYER_SALUTE1,
  [ServerPlayerActionType.Rush]: PlayerAction.PLAYER_RUSH1,
  [ServerPlayerActionType.Scissors]: PlayerAction.PLAYER_SCISSORS,
  [ServerPlayerActionType.Rock]: PlayerAction.PLAYER_ROCK,
  [ServerPlayerActionType.Paper]: PlayerAction.PLAYER_PAPER,
  [ServerPlayerActionType.Hustle]: PlayerAction.PLAYER_HUSTLE,
  [ServerPlayerActionType.Provocation]: PlayerAction.PLAYER_PROVOCATION,
  [ServerPlayerActionType.LookAround]: PlayerAction.PLAYER_LOOK_AROUND,
  [ServerPlayerActionType.Cheers]: PlayerAction.PLAYER_CHEERS,
  [ServerPlayerActionType.Jack1]: PlayerAction.PLAYER_JACK_1,
  [ServerPlayerActionType.Jack2]: PlayerAction.PLAYER_JACK_2,
  [ServerPlayerActionType.Santa1_1]: PlayerAction.PLAYER_SANTA_1,
  [ServerPlayerActionType.Santa1_2]: PlayerAction.PLAYER_SANTA_1,
  [ServerPlayerActionType.Santa1_3]: PlayerAction.PLAYER_SANTA_1,
  [ServerPlayerActionType.Santa2_1]: PlayerAction.PLAYER_SANTA_2,
  [ServerPlayerActionType.Santa2_2]: PlayerAction.PLAYER_SANTA_2,
  [ServerPlayerActionType.Santa2_3]: PlayerAction.PLAYER_SANTA_2,
};
