export const MODEL_WORLD_OBJECT = 0;
export const MODEL_TREE01 = 0;
export const MODEL_GRASS01 = 20;
export const MODEL_STONE01 = 30;
export const MODEL_STONE_STATUE01 = 40;
export const MODEL_STONE_STATUE02 = 41;
export const MODEL_STONE_STATUE03 = 42;
export const MODEL_STEEL_STATUE = 43;
export const MODEL_TOMB01 = 44;
export const MODEL_TOMB02 = 45;
export const MODEL_TOMB03 = 46;
export const MODEL_FIRE_LIGHT01 = 50;
export const MODEL_FIRE_LIGHT02 = 51;
export const MODEL_BONFIRE = 52;
export const MODEL_DUNGEON_GATE = 55;
export const MODEL_MERCHANT_ANIMAL01 = 56;
export const MODEL_MERCHANT_ANIMAL02 = 57;
export const MODEL_TREASURE_DRUM = 58;
export const MODEL_TREASURE_CHEST = 59;
export const MODEL_SHIP = 60;
export const MODEL_STEEL_WALL01 = 65;
export const MODEL_STEEL_WALL02 = 66;
export const MODEL_STEEL_WALL03 = 67;
export const MODEL_STEEL_DOOR = 68;
export const MODEL_STONE_WALL01 = 69;
export const MODEL_STONE_WALL02 = 70;
export const MODEL_STONE_WALL03 = 71;
export const MODEL_STONE_WALL04 = 72;
export const MODEL_STONE_WALL05 = 73;
export const MODEL_STONE_WALL06 = 74;
export const MODEL_MU_WALL01 = 75;
export const MODEL_MU_WALL02 = 76;
export const MODEL_MU_WALL03 = 77;
export const MODEL_MU_WALL04 = 78;
export const MODEL_BRIDGE = 80;
export const MODEL_FENCE01 = 81;
export const MODEL_FENCE02 = 82;
export const MODEL_FENCE03 = 83;
export const MODEL_FENCE04 = 84;
export const MODEL_BRIDGE_STONE = 85;
export const MODEL_STREET_LIGHT = 90;
export const MODEL_CANNON01 = 91;
export const MODEL_CANNON02 = 92;
export const MODEL_CANNON03 = 93;
export const MODEL_CURTAIN = 95;
export const MODEL_SIGN01 = 96;
export const MODEL_SIGN02 = 97;
export const MODEL_CARRIAGE01 = 98;
export const MODEL_CARRIAGE02 = 99;
export const MODEL_CARRIAGE03 = 100;
export const MODEL_CARRIAGE04 = 101;
export const MODEL_STRAW01 = 102;
export const MODEL_STRAW02 = 103;
export const MODEL_WATERSPOUT = 105;
export const MODEL_WELL01 = 106;
export const MODEL_WELL02 = 107;
export const MODEL_WELL03 = 108;
export const MODEL_WELL04 = 109;
export const MODEL_HANGING = 110;
export const MODEL_STAIR = 111;
export const MODEL_HOUSE01 = 115;
export const MODEL_HOUSE02 = 116;
export const MODEL_HOUSE03 = 117;
export const MODEL_HOUSE04 = 118;
export const MODEL_HOUSE05 = 119;
export const MODEL_TENT = 120;
export const MODEL_HOUSE_WALL01 = 121;
export const MODEL_HOUSE_WALL02 = 122;
export const MODEL_HOUSE_WALL03 = 123;
export const MODEL_HOUSE_WALL04 = 124;
export const MODEL_HOUSE_WALL05 = 125;
export const MODEL_HOUSE_WALL06 = 126;
export const MODEL_HOUSE_ETC01 = 127;
export const MODEL_HOUSE_ETC02 = 128;
export const MODEL_HOUSE_ETC03 = 129;
export const MODEL_LIGHT01 = 130;
export const MODEL_LIGHT02 = 131;
export const MODEL_LIGHT03 = 132;
export const MODEL_POSE_BOX = 133;
export const MODEL_FURNITURE01 = 140;
export const MODEL_FURNITURE02 = 141;
export const MODEL_FURNITURE03 = 142;
export const MODEL_FURNITURE04 = 143;
export const MODEL_FURNITURE05 = 144;
export const MODEL_FURNITURE06 = 145;
export const MODEL_FURNITURE07 = 146;
export const MODEL_CANDLE = 150;
export const MODEL_BEER01 = 151;
export const MODEL_BEER02 = 152;
export const MODEL_BEER03 = 153;
export const MODEL_HERO_CHAIR = 154;
export const MODEL_HERO_GUARD = 155;
export const MODEL_MURDERER_DOG = 156;
export const MAX_WORLD_OBJECTS = 160;
export const MODEL_LOGO = 160;
export const MODEL_WAVEBYSHIP = 161;
export const MODEL_MUGAME = 162;
export const MODEL_LOGOSUN = 163;
export const MODEL_CARD = 164;
export const MODEL_FACE = 168;
export const MODEL_BIRD01 = 175;
export const MODEL_BUTTERFLY01 = 175;
export const MODEL_BAT01 = 176;
export const MODEL_RAT01 = 177;
export const MODEL_BUG01 = 178;
export const MODEL_FISH01 = 179;
export const MODEL_GHOST = 180;
export const MODEL_DRAGON = 181;
export const MODEL_LOGIN_WARP = 182;
export const MODEL_CLOUD = 188;
export const MODEL_CROW = 189;
export const MODEL_SHINE = 190;
export const MODEL_EAGLE = 191;
export const MODEL_MAP_TORNADO = 192;
export const MODEL_GM_CHARACTER = 193;
export const MODEL_XMAS_EVENT_CHA_SSANTA = 194;
export const MODEL_XMAS_EVENT_CHA_SNOWMAN = 195;
export const MODEL_XMAS_EVENT_CHA_DEER = 196;
export const MODEL_XMAS_EVENT_CHANGE_GIRL = 197;
export const MODEL_XMAS_EVENT_EARRING = 198;
export const MODEL_XMAS_EVENT_ICEHEART = 199;
export const MODEL_XMAS_EVENT_BOX = 200;
export const MODEL_XMAS_EVENT_CANDY = 201;
export const MODEL_XMAS_EVENT_TREE = 202;
export const MODEL_XMAS_EVENT_SOCKS = 203;
export const MODEL_NEWYEARSDAY_EVENT_BEKSULKI = 204;
export const MODEL_NEWYEARSDAY_EVENT_CANDY = 205;
export const MODEL_NEWYEARSDAY_EVENT_HOTPEPPER_GREEN = 206;
export const MODEL_NEWYEARSDAY_EVENT_HOTPEPPER_RED = 207;
export const MODEL_NEWYEARSDAY_EVENT_PIG = 208;
export const MODEL_NEWYEARSDAY_EVENT_YUT = 209;
export const MODEL_NEWYEARSDAY_EVENT_MONEY = 210;
export const MODEL_MOONHARVEST_GAM = 211;
export const MODEL_MOONHARVEST_SONGPUEN1 = 212;
export const MODEL_MOONHARVEST_SONGPUEN2 = 213;
export const MODEL_MOONHARVEST_MOON = 214;
export const MODEL_LIGHTNING_ORB = 215;
export const MODEL_CHAIN_LIGHTNING = 216;
export const MODEL_ALICE_BUFFSKILL_EFFECT = 217;
export const MODEL_ALICE_BUFFSKILL_EFFECT2 = 218;
export const MODEL_ALICE_DRAIN_LIFE = 219;
export const MODEL_RAKLION_BOSS_CRACKEFFECT = 220;
export const MODEL_RAKLION_BOSS_MAGIC = 221;
export const MODEL_LIGHTNING_SHOCK = 222;
export const MODEL_MOVE_TARGETPOSITION_EFFECT = 223;
export const MODEL_SKILL_BEGIN = 224;
export const MODEL_DARK_HORSE = 225;
export const MODEL_DARK_SPIRIT = 226;
export const MODEL_ICE = 227;
export const MODEL_FIRE = 228;
export const MODEL_POISON = 229;
export const MODEL_WOLF = 230;
export const MODEL_WARCRAFT = 231;
export const MODEL_UNICON = 232;
export const MODEL_BLOOD = 233;
export const MODEL_STONE1 = 234;
export const MODEL_STONE2 = 235;
export const MODEL_ICE_SMALL = 236;
export const MODEL_CIRCLE = 237;
export const MODEL_CIRCLE_LIGHT = 238;
export const MODEL_MAGIC1 = 239;
export const MODEL_MAGIC2 = 240;
export const MODEL_STORM = 241;
export const MODEL_LASER = 242;
export const MODEL_SKELETON1 = 243;
export const MODEL_SKELETON2 = 244;
export const MODEL_SKELETON3 = 245;
export const MODEL_SKELETON_PCBANG = 246;
export const MODEL_HALLOWEEN = 247;
export const MODEL_HALLOWEEN_EX = 248;
export const MODEL_HALLOWEEN_CANDY_BLUE = 249;
export const MODEL_HALLOWEEN_CANDY_ORANGE = 250;
export const MODEL_HALLOWEEN_CANDY_RED = 251;
export const MODEL_HALLOWEEN_CANDY_YELLOW = 252;
export const MODEL_HALLOWEEN_CANDY_HOBAK = 253;
export const MODEL_HALLOWEEN_CANDY_STAR = 254;
export const MODEL_CURSEDTEMPLE_ALLIED_PLAYER = 255;
export const MODEL_CURSEDTEMPLE_ILLUSION_PLAYER = 256;
export const MODEL_WOOSISTONE = 257;
export const MODEL_SAW = 258;
export const MODEL_BONE1 = 259;
export const MODEL_BONE2 = 260;
export const MODEL_SNOW1 = 261;
export const MODEL_SNOW2 = 262;
export const MODEL_SNOW3 = 263;
export const MODEL_DUNGEON_STONE01 = 264;
export const MODEL_ARROW = 265;
export const MODEL_ARROW_STEEL = 266;
export const MODEL_ARROW_THUNDER = 267;
export const MODEL_ARROW_LASER = 268;
export const MODEL_ARROW_V = 269;
export const MODEL_ARROW_SAW = 270;
export const MODEL_ARROW_NATURE = 271;
export const MODEL_ARROW_BOMB = 272;
export const MODEL_ARROW_WING = 273;
export const MODEL_PROTECT = 274;
export const MODEL_BIG_STONE1 = 275;
export const MODEL_BIG_STONE2 = 276;
export const MODEL_BIG_METEO1 = 277;
export const MODEL_BIG_METEO2 = 278;
export const MODEL_BIG_METEO3 = 279;
export const MODEL_METEO1 = 280;
export const MODEL_METEO2 = 281;
export const MODEL_MAGIC_CIRCLE1 = 282;
export const MODEL_ARROW_TANKER = 283;
export const MODEL_ARROW_TANKER_HIT = 284;
export const MODEL_BOSS_HEAD = 285;
export const MODEL_PRINCESS = 286;
export const MODEL_BALL = 287;
export const MODEL_BOSS_ATTACK = 288;
export const MODEL_SKILL_WHEEL1 = 289;
export const MODEL_SKILL_WHEEL2 = 290;
export const MODEL_SKILL_BLAST = 291;
export const MODEL_SKILL_INFERNO = 292;
export const MODEL_ARROW_DOUBLE = 293;
export const MODEL_ARROW_HOLY = 294;
export const MODEL_ARROW_SPARK = 295;
export const MODEL_ARROW_RING = 296;
export const MODEL_ARROW_DARKSTINGER = 297;
export const MODEL_FEATHER = 298;
export const MODEL_FEATHER_FOREIGN = 299;
export const MODEL_SKILL_FURY_STRIKE = 300;
export const MODEL_WAVE = 309;
export const MODEL_TAIL = 310;
export const MODEL_PIERCING = 311;
export const MODEL_WAVE_FORCE = 313;
export const MODEL_BLIZZARD = 314;
export const MODEL_MAGIC_CAPSULE2 = 315;
export const MODEL_STONE_COFFIN = 316;
export const MODEL_GATE = 318;
export const MODEL_ARROW_BEST_CROSSBOW = 320;
export const MODEL_SPEARSKILL = 319;
export const MODEL_PEGASUS = 320;
export const MODEL_ARROW_DRILL = 321;
export const MODEL_COMBO = 322;
export const MODEL_AIR_FORCE = 323;
export const MODEL_WAVES = 324;
export const MODEL_PIERCING2 = 325;
export const MODEL_PIER_PART = 326;
export const MODEL_DARKLORD_SKILL = 327;
export const MODEL_GROUND_STONE = 328;
export const MODEL_GROUND_STONE2 = 329;
export const MODEL_WATER_WAVE = 330;
export const MODEL_SKULL = 331;
export const MODEL_LACEARROW = 332;
export const MODEL_CUNDUN_PART1 = 333;
export const MODEL_CUNDUN_PART2 = 334;
export const MODEL_CUNDUN_PART3 = 335;
export const MODEL_CUNDUN_PART4 = 336;
export const MODEL_CUNDUN_PART5 = 337;
export const MODEL_CUNDUN_PART6 = 338;
export const MODEL_CUNDUN_PART7 = 339;
export const MODEL_CUNDUN_PART8 = 340;
export const MODEL_CUNDUN_DRAGON_HEAD = 341;
export const MODEL_CUNDUN_PHOENIX = 342;
export const MODEL_CUNDUN_GHOST = 343;
export const MODEL_CUNDUN_SKILL = 344;
export const MODEL_MANY_FLAG = 345;
export const MODEL_WEBZEN_MARK = 346;
export const MODEL_FLY_BIG_STONE1 = 347;
export const MODEL_FLY_BIG_STONE2 = 348;
export const MODEL_BIG_STONE_PART1 = 349;
export const MODEL_BIG_STONE_PART2 = 350;
export const MODEL_WALL_PART1 = 351;
export const MODEL_WALL_PART2 = 352;
export const MODEL_GATE_PART1 = 353;
export const MODEL_GATE_PART2 = 354;
export const MODEL_GATE_PART3 = 355;
export const MODEL_AURORA = 356;
export const MODEL_TOWER_GATE_PLANE = 357;
export const MODEL_STUN_STONE = 358;
export const MODEL_SKIN_SHELL = 359;
export const MODEL_MANA_RUNE = 360;
export const MODEL_SKILL_JAVELIN = 361;
export const MODEL_ARROW_IMPACT = 362;
export const MODEL_SWORD_FORCE = 363;
export const MODEL_GOLEM_STONE = 364;
export const MODEL_FISSURE = 365;
export const MODEL_FISSURE_LIGHT = 366;
export const MODEL_SKILL_FISSURE = 367;
export const MODEL_PROTECTGUILD = 368;
export const MODEL_TREE_ATTACK = 369;
export const MODEL_WARP = 370;
export const MODEL_WARP2 = 371;
export const MODEL_WARP3 = 372;
export const MODEL_WARP4 = 373;
export const MODEL_WARP5 = 374;
export const MODEL_WARP6 = 375;
export const MODEL_DARK_ELF_SKILL = 376;
export const MODEL_BALGAS_SKILL = 377;
export const MODEL_DEATH_SPI_SKILL = 378;
export const MODEL_SCOLPION = 379;
export const MODEL_BUG_CRY1ST = 380;
export const MODEL_FENRIR_BLACK = 381;
export const MODEL_FENRIR_RED = 382;
export const MODEL_FENRIR_BLUE = 383;
export const MODEL_FENRIR_GOLD = 384;
export const MODEL_FENRIR_THUNDER = 385;
export const MODEL_FENRIR_FOOT_THUNDER = 386;
export const MODEL_FENRIR_SKILL_THUNDER = 387;
export const MODEL_FENRIR_SKILL_DAMAGE = 388;
export const MODEL_ARROW_AUTOLOAD = 389;
export const MODEL_SHIELD_CRASH = 390;
export const MODEL_SHIELD_CRASH2 = 391;
export const MODEL_INFINITY_ARROW = 392;
export const MODEL_INFINITY_ARROW1 = 393;
export const MODEL_INFINITY_ARROW2 = 394;
export const MODEL_INFINITY_ARROW3 = 395;
export const MODEL_INFINITY_ARROW4 = 396;
export const MODEL_IRON_RIDER_ARROW = 397;
export const MODEL_KENTAUROS_ARROW = 398;
export const MODEL_BLADE_SKILL = 399;
export const MODEL_TWINTAIL_EFFECT = 400;
export const MODEL_STORM2 = 401;
export const MODEL_SUMMON = 402;
export const MODEL_STORM3 = 403;
export const MODEL_MAYASTAR = 404;
export const MODEL_MAYASTONE1 = 405;
export const MODEL_MAYASTONE2 = 406;
export const MODEL_MAYASTONE3 = 407;
export const MODEL_MAYASTONE4 = 408;
export const MODEL_MAYASTONE5 = 409;
export const MODEL_MAYASTONEFIRE = 410;
export const MODEL_MAYAHANDSKILL = 411;
export const MODEL_DARK_SCREAM = 412;
export const MODEL_DARK_SCREAM_FIRE = 413;
export const MODEL_CURSEDTEMPLE_HOLYITEM = 414;
export const MODEL_CURSEDTEMPLE_PRODECTION_SKILL = 415;
export const MODEL_CURSEDTEMPLE_RESTRAINT_SKILL = 416;
export const MODEL_FALL_STONE_EFFECT = 417;
export const MODEL_CURSEDTEMPLE_STATUE_PART1 = 418;
export const MODEL_CURSEDTEMPLE_STATUE_PART2 = 419;
export const MODEL_CHANGE_UP_EFF = 420;
export const MODEL_CHANGE_UP_NASA = 421;
export const MODEL_CHANGE_UP_CYLINDER = 422;
export const MODEL_TOTEMGOLEM_PART1 = 423;
export const MODEL_TOTEMGOLEM_PART2 = 424;
export const MODEL_TOTEMGOLEM_PART3 = 425;
export const MODEL_TOTEMGOLEM_PART4 = 426;
export const MODEL_TOTEMGOLEM_PART5 = 427;
export const MODEL_TOTEMGOLEM_PART6 = 428;
export const MODEL_SUMMONER_WRISTRING_EFFECT = 429;
export const MODEL_SUMMONER_EQUIP_HEAD_SAHAMUTT = 430;
export const MODEL_SUMMONER_EQUIP_HEAD_NEIL = 431;
export const MODEL_SUMMONER_EQUIP_HEAD_LAGUL = 432;
export const MODEL_SUMMONER_CASTING_EFFECT1 = 433;
export const MODEL_SUMMONER_CASTING_EFFECT11 = 434;
export const MODEL_SUMMONER_CASTING_EFFECT111 = 435;
export const MODEL_SUMMONER_CASTING_EFFECT2 = 436;
export const MODEL_SUMMONER_CASTING_EFFECT22 = 437;
export const MODEL_SUMMONER_CASTING_EFFECT222 = 438;
export const MODEL_SUMMONER_CASTING_EFFECT4 = 439;
export const MODEL_SUMMONER_SUMMON_SAHAMUTT = 440;
export const MODEL_SUMMONER_SUMMON_NEIL = 441;
export const MODEL_SUMMONER_SUMMON_LAGUL = 442;
export const MODEL_SUMMONER_SUMMON_NEIL_NIFE1 = 443;
export const MODEL_SUMMONER_SUMMON_NEIL_NIFE2 = 444;
export const MODEL_SUMMONER_SUMMON_NEIL_NIFE3 = 445;
export const MODEL_SUMMONER_SUMMON_NEIL_GROUND1 = 446;
export const MODEL_SUMMONER_SUMMON_NEIL_GROUND2 = 447;
export const MODEL_SUMMONER_SUMMON_NEIL_GROUND3 = 448;
export const MODEL_SHADOW_PAWN_ANKLE_LEFT = 449;
export const MODEL_SHADOW_PAWN_ANKLE_RIGHT = 450;
export const MODEL_SHADOW_PAWN_BELT = 451;
export const MODEL_SHADOW_PAWN_CHEST = 452;
export const MODEL_SHADOW_PAWN_HELMET = 453;
export const MODEL_SHADOW_PAWN_KNEE_LEFT = 454;
export const MODEL_SHADOW_PAWN_KNEE_RIGHT = 455;
export const MODEL_SHADOW_PAWN_WRIST_LEFT = 456;
export const MODEL_SHADOW_PAWN_WRIST_RIGHT = 457;
export const MODEL_SHADOW_KNIGHT_ANKLE_LEFT = 458;
export const MODEL_SHADOW_KNIGHT_ANKLE_RIGHT = 459;
export const MODEL_SHADOW_KNIGHT_BELT = 460;
export const MODEL_SHADOW_KNIGHT_CHEST = 461;
export const MODEL_SHADOW_KNIGHT_HELMET = 462;
export const MODEL_SHADOW_KNIGHT_KNEE_LEFT = 463;
export const MODEL_SHADOW_KNIGHT_KNEE_RIGHT = 464;
export const MODEL_SHADOW_KNIGHT_WRIST_LEFT = 465;
export const MODEL_SHADOW_KNIGHT_WRIST_RIGHT = 466;
export const MODEL_SHADOW_ROOK_ANKLE_LEFT = 467;
export const MODEL_SHADOW_ROOK_ANKLE_RIGHT = 468;
export const MODEL_SHADOW_ROOK_BELT = 469;
export const MODEL_SHADOW_ROOK_CHEST = 470;
export const MODEL_SHADOW_ROOK_HELMET = 471;
export const MODEL_SHADOW_ROOK_KNEE_LEFT = 472;
export const MODEL_SHADOW_ROOK_KNEE_RIGHT = 473;
export const MODEL_SHADOW_ROOK_WRIST_LEFT = 474;
export const MODEL_SHADOW_ROOK_WRIST_RIGHT = 475;
export const MODEL_ICE_GIANT_PART1 = 476;
export const MODEL_ICE_GIANT_PART2 = 477;
export const MODEL_ICE_GIANT_PART3 = 478;
export const MODEL_ICE_GIANT_PART4 = 479;
export const MODEL_ICE_GIANT_PART5 = 480;
export const MODEL_ICE_GIANT_PART6 = 481;
export const MODEL_EFFECT_SAPITRES_ATTACK = 482;
export const MODEL_EFFECT_SAPITRES_ATTACK_1 = 483;
export const MODEL_EFFECT_SAPITRES_ATTACK_2 = 484;
export const MODEL_EFFECT_THUNDER_NAPIN_ATTACK_1 = 485;
export const MODEL_EFFECT_SKURA_ITEM = 486;
export const MODEL_EFFECT_BROKEN_ICE0 = 487;
export const MODEL_EFFECT_BROKEN_ICE1 = 488;
export const MODEL_EFFECT_BROKEN_ICE2 = 489;
export const MODEL_EFFECT_BROKEN_ICE3 = 490;
export const MODEL_EFFECT_UMBRELLA_LIGHT = 491;
export const MODEL_DESAIR = 492;
export const MODEL_EFFECT_TRACE = 493;
export const MODEL_STAR_SHINE = 494;
export const MODEL_BLOW_OF_DESTRUCTION = 495;
export const MODEL_NIGHTWATER_01 = 496;
export const MODEL_KNIGHT_PLANCRACK_A = 497;
export const MODEL_KNIGHT_PLANCRACK_B = 498;
export const MODEL_SWELL_OF_MAGICPOWER = 499;
export const MODEL_SWELL_OF_MAGICPOWER_GUIDE = 500;
export const MODEL_ARROWSRE06 = 501;
export const MODEL_SWELL_OF_MAGICPOWER_BUFF_EFF = 502;
export const MODEL_EFFECT_FLAME_STRIKE = 503;
export const MODEL_STREAMOFICEBREATH = 504;
export const MODEL_1_STREAMBREATHFIRE = 505;
export const MODEL_ARROW_GAMBLE = 506;
export const MODEL_PKFIELD_ASSASSIN_EFFECT_GREEN_HEAD = 507;
export const MODEL_PKFIELD_ASSASSIN_EFFECT_RED_HEAD = 508;
export const MODEL_PKFIELD_ASSASSIN_EFFECT_GREEN_BODY = 509;
export const MODEL_PKFIELD_ASSASSIN_EFFECT_RED_BODY = 510;
export const MODEL_LAVAGIANT_FOOTPRINT_R = 511;
export const MODEL_LAVAGIANT_FOOTPRINT_V = 512;
export const MODEL_EFFECT_FIRE_HIK3_MONO = 513;
export const MODEL_PROJECTILE = 514;
export const MODEL_DOOR_CRUSH_EFFECT = 515;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE01 = 516;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE02 = 517;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE03 = 518;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE04 = 519;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE05 = 520;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE06 = 521;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE07 = 522;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE08 = 523;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE09 = 524;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE10 = 525;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE11 = 526;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE12 = 527;
export const MODEL_DOOR_CRUSH_EFFECT_PIECE13 = 528;
export const MODEL_STATUE_CRUSH_EFFECT = 529;
export const MODEL_STATUE_CRUSH_EFFECT_PIECE01 = 530;
export const MODEL_STATUE_CRUSH_EFFECT_PIECE02 = 531;
export const MODEL_STATUE_CRUSH_EFFECT_PIECE03 = 532;
export const MODEL_STATUE_CRUSH_EFFECT_PIECE04 = 533;
export const MODEL_PANDA = 534;
export const MODEL_EMPIREGUARDIANBOSS_SKILLEFF01_GENERALATTACK = 535;
export const MODEL_EMPIREGUARDIANBOSS_SKILLEFF02_BLOODATTACK = 536;
export const MODEL_EMPIREGUARDIANBOSS_SKILLEFF03_GIGANTIC = 537;
export const MODEL_EMPIREGUARDIANBOSS_SKILLEFF04_FRAMESTRIKE = 538;
export const MODEL_SWORDLEFT01_EMPIREGUARDIAN_BOSS_GAION_ = 539;
export const MODEL_SWORDLEFT02_EMPIREGUARDIAN_BOSS_GAION_ = 540;
export const MODEL_SWORDRIGHT01_EMPIREGUARDIAN_BOSS_GAION_ = 541;
export const MODEL_SWORDRIGHT02_EMPIREGUARDIAN_BOSS_GAION_ = 542;
export const MODEL_SWORDMAIN01_EMPIREGUARDIAN_BOSS_GAION_ = 543;
export const MODEL_EMPIREGUARDIAN_BLOW_OF_DESTRUCTION = 544;
export const MODEL_EFFECT_UMBRELLA_DIE = 545;
export const MODEL_EFFECT_UMBRELLA_GOLD = 546;
export const MODEL_DOPPELGANGER_SLIME_CHIP = 547;
export const MODEL_EMPIREGUARDIANBOSS_FRAMESTRIKE = 548;
export const MODEL_DEASULER = 549;
export const MODEL_EFFECT_EG_GUARDIANDEFENDER_ATTACK2 = 550;
export const MODEL_EFFECT_SD_AURA = 551;
export const MODEL_SKELETON_CHANGED = 552;
export const MODEL_15GRADE_ARMOR_OBJ_ARMLEFT = 553;
export const MODEL_15GRADE_ARMOR_OBJ_ARMRIGHT = 554;
export const MODEL_15GRADE_ARMOR_OBJ_BODYLEFT = 555;
export const MODEL_15GRADE_ARMOR_OBJ_BODYRIGHT = 556;
export const MODEL_15GRADE_ARMOR_OBJ_BOOTLEFT = 557;
export const MODEL_15GRADE_ARMOR_OBJ_BOOTRIGHT = 558;
export const MODEL_15GRADE_ARMOR_OBJ_HEAD = 559;
export const MODEL_15GRADE_ARMOR_OBJ_PANTLEFT = 560;
export const MODEL_15GRADE_ARMOR_OBJ_PANTRIGHT = 561;
export const MODEL_EX01_SHADOW_MASTER_ANKLE_LEFT = 562;
export const MODEL_EX01_SHADOW_MASTER_ANKLE_RIGHT = 563;
export const MODEL_EX01_SHADOW_MASTER_BELT = 564;
export const MODEL_EX01_SHADOW_MASTER_CHEST = 565;
export const MODEL_EX01_SHADOW_MASTER_HELMET = 566;
export const MODEL_EX01_SHADOW_MASTER_KNEE_LEFT = 567;
export const MODEL_EX01_SHADOW_MASTER_KNEE_RIGHT = 568;
export const MODEL_EX01_SHADOW_MASTER_WRIST_LEFT = 569;
export const MODEL_EX01_SHADOW_MASTER_WRIST_RIGHT = 570;
export const MODEL_CONDRA_ARM_L = 571;
export const MODEL_CONDRA_ARM_L2 = 572;
export const MODEL_CONDRA_SHOULDER = 573;
export const MODEL_CONDRA_ARM_R = 574;
export const MODEL_CONDRA_ARM_R2 = 575;
export const MODEL_CONDRA_CONE_L = 576;
export const MODEL_CONDRA_CONE_R = 577;
export const MODEL_CONDRA_PELVIS = 578;
export const MODEL_CONDRA_STOMACH = 579;
export const MODEL_CONDRA_NECK = 580;
export const MODEL_CONDRA_STONE = 581;
export const MODEL_CONDRA_STONE1 = 582;
export const MODEL_CONDRA_STONE2 = 583;
export const MODEL_CONDRA_STONE3 = 584;
export const MODEL_CONDRA_STONE4 = 585;
export const MODEL_CONDRA_STONE5 = 586;
export const MODEL_NARCONDRA_ARM_L = 587;
export const MODEL_NARCONDRA_ARM_L2 = 588;
export const MODEL_NARCONDRA_SHOULDER_L = 589;
export const MODEL_NARCONDRA_SHOULDER_R = 590;
export const MODEL_NARCONDRA_ARM_R = 591;
export const MODEL_NARCONDRA_ARM_R2 = 592;
export const MODEL_NARCONDRA_ARM_R3 = 593;
export const MODEL_NARCONDRA_CONE_1 = 594;
export const MODEL_NARCONDRA_CONE_2 = 595;
export const MODEL_NARCONDRA_CONE_3 = 596;
export const MODEL_NARCONDRA_CONE_4 = 597;
export const MODEL_NARCONDRA_CONE_5 = 598;
export const MODEL_NARCONDRA_CONE_6 = 599;
export const MODEL_NARCONDRA_PELVIS = 600;
export const MODEL_NARCONDRA_STOMACH = 601;
export const MODEL_NARCONDRA_NECK = 602;
export const MODEL_NARCONDRA_STONE = 603;
export const MODEL_NARCONDRA_STONE1 = 604;
export const MODEL_NARCONDRA_STONE2 = 605;
export const MODEL_NARCONDRA_STONE3 = 606;
export const MODEL_SWORD_32_LEFT = 607;
export const MODEL_SWORD_32_RIGHT = 608;
export const MODEL_SWORD_33_LEFT = 609;
export const MODEL_SWORD_33_RIGHT = 610;
export const MODEL_SWORD_34_LEFT = 611;
export const MODEL_SWORD_34_RIGHT = 612;
export const MODEL_SWORD_35_LEFT = 613;
export const MODEL_SWORD_35_RIGHT = 614;
export const MODEL_SWORD_35_WING = 615;
export const MODEL_WOLF_HEAD_EFFECT = 616;
export const MODEL_ARMORINVEN_60 = 617;
export const MODEL_ARMORINVEN_61 = 618;
export const MODEL_ARMORINVEN_62 = 619;
export const MODEL_DOWN_ATTACK_DUMMY_L = 620;
export const MODEL_DOWN_ATTACK_DUMMY_R = 621;
export const MODEL_SHOCKWAVE01 = 622;
export const MODEL_SHOCKWAVE02 = 623;
export const MODEL_SHOCKWAVE_SPIN01 = 624;
export const MODEL_WINDFOCE = 625;
export const MODEL_WINDFOCE_MIRROR = 626;
export const MODEL_WOLF_HEAD_EFFECT2 = 627;
export const MODEL_SHOCKWAVE_GROUND01 = 628;
export const MODEL_DRAGON_KICK_DUMMY = 629;
export const MODEL_DRAGON_LOWER_DUMMY = 630;
export const MODEL_TARGETMON_EFFECT = 631;
export const MODEL_SHOCKWAVE03 = 632;
export const MODEL_VOLCANO_OF_MONK = 633;
export const MODEL_VOLCANO_STONE = 634;
export const MODEL_ARMORINVEN_74 = 635;
export const MODEL_PHOENIX_SHOT = 636;
export const MODEL_WINDSPIN01 = 637;
export const MODEL_WINDSPIN02 = 638;
export const MODEL_WINDSPIN03 = 639;
export const MODEL_SKILL_END = 640;

export const MODEL_MONSTER01 = MODEL_SKILL_END + 1;

export const MODEL_NPC_BEGIN = 1041;
export const MODEL_MERCHANT_FEMALE = 1042;
export const MODEL_MERCHANT_MAN = 1043;
export const MODEL_MERCHANT_GIRL = 1044;
export const MODEL_SMITH = 1045;
export const MODEL_SCIENTIST = 1046;
export const MODEL_SNOW_MERCHANT = 1047;
export const MODEL_SNOW_SMITH = 1048;
export const MODEL_SNOW_WIZARD = 1049;
export const MODEL_ELF_WIZARD = 1050;
export const MODEL_ELF_MERCHANT = 1051;
export const MODEL_MASTER = 1052;
export const MODEL_STORAGE = 1053;
export const MODEL_TOURNAMENT = 1054;
export const MODEL_MIX_NPC = 1055;
export const MODEL_NPC_DEVILSQUARE = 1056;
export const MODEL_MERCHANT_FEMALE_HEAD = 1057;
export const MODEL_MERCHANT_FEMALE_UPPER = MODEL_MERCHANT_FEMALE_HEAD + 2;
export const MODEL_MERCHANT_FEMALE_LOWER = MODEL_MERCHANT_FEMALE_UPPER + 2;
export const MODEL_MERCHANT_FEMALE_GLOVES = MODEL_MERCHANT_FEMALE_LOWER + 2;
export const MODEL_MERCHANT_FEMALE_BOOTS = MODEL_MERCHANT_FEMALE_GLOVES + 2;
export const MODEL_MERCHANT_MAN_HEAD = MODEL_MERCHANT_FEMALE_BOOTS + 2;
export const MODEL_MERCHANT_MAN_UPPER = MODEL_MERCHANT_MAN_HEAD + 2;
export const MODEL_MERCHANT_MAN_GLOVES = MODEL_MERCHANT_MAN_UPPER + 2;
export const MODEL_MERCHANT_MAN_BOOTS = MODEL_MERCHANT_MAN_GLOVES + 2;
export const MODEL_MERCHANT_GIRL_HEAD = MODEL_MERCHANT_MAN_BOOTS + 2;
export const MODEL_MERCHANT_GIRL_UPPER = MODEL_MERCHANT_GIRL_HEAD + 2;
export const MODEL_MERCHANT_GIRL_LOWER = MODEL_MERCHANT_GIRL_UPPER + 2;
export const MODEL_NPC_SEVINA = MODEL_MERCHANT_GIRL_LOWER + 2;
export const MODEL_NPC_ARCHANGEL = MODEL_NPC_SEVINA + 1;
export const MODEL_NPC_ARCHANGEL_MESSENGER = MODEL_NPC_ARCHANGEL + 1;
export const MODEL_DEVIAS_TRADER = MODEL_NPC_ARCHANGEL_MESSENGER + 1;
export const MODEL_NPC_BREEDER = MODEL_DEVIAS_TRADER + 1;
export const MODEL_ANGEL = MODEL_DEVIAS_TRADER + 2;
export const MODEL_KALIMA_SHOP = MODEL_ANGEL + 1;
export const MODEL_BC_NPC1 = MODEL_KALIMA_SHOP + 1;
export const MODEL_BC_NPC2 = MODEL_BC_NPC1 + 1;
export const MODEL_BC_BOX = MODEL_BC_NPC2 + 1;
export const MODEL_NPC_CAPATULT_ATT = MODEL_BC_BOX + 1;
export const MODEL_NPC_CAPATULT_DEF = MODEL_NPC_CAPATULT_ATT + 1;
export const MODEL_NPC_SENATUS = MODEL_NPC_CAPATULT_DEF + 1;
export const MODEL_NPC_GATE_SWITCH = MODEL_NPC_SENATUS + 1;
export const MODEL_NPC_CROWN = MODEL_NPC_GATE_SWITCH + 1;
export const MODEL_NPC_CHECK_FLOOR = MODEL_NPC_CROWN + 1;
export const MODEL_NPC_CLERK = MODEL_NPC_CHECK_FLOOR + 1;
export const MODEL_NPC_BARRIER = MODEL_NPC_CLERK + 1;
export const MODEL_NPC_SERBIS = MODEL_NPC_BARRIER + 1;
export const MODEL_NPC_SERBIS_DONKEY = MODEL_NPC_SERBIS + 1;
export const MODEL_NPC_SERBIS_FLAG = MODEL_NPC_SERBIS_DONKEY + 1;
export const MODEL_CRYWOLF_STATUE = MODEL_NPC_SERBIS_FLAG + 1;
export const MODEL_CRYWOLF_ALTAR1 = MODEL_CRYWOLF_STATUE + 1;
export const MODEL_CRYWOLF_ALTAR2 = MODEL_CRYWOLF_ALTAR1 + 1;
export const MODEL_CRYWOLF_ALTAR3 = MODEL_CRYWOLF_ALTAR2 + 1;
export const MODEL_CRYWOLF_ALTAR4 = MODEL_CRYWOLF_ALTAR3 + 1;
export const MODEL_CRYWOLF_ALTAR5 = MODEL_CRYWOLF_ALTAR4 + 1;
export const MODEL_KANTURU2ND_ENTER_NPC = MODEL_CRYWOLF_ALTAR5 + 1;
export const MODEL_TRAP_CANON = MODEL_KANTURU2ND_ENTER_NPC + 1;
export const MODEL_SMELTING_NPC = MODEL_TRAP_CANON + 1;
export const MODEL_REFINERY_NPC = MODEL_SMELTING_NPC + 1;
export const MODEL_RECOVERY_NPC = MODEL_REFINERY_NPC + 1;
export const MODEL_WEDDING_NPC = MODEL_RECOVERY_NPC + 1;
export const MODEL_NPC_DEVIN = MODEL_WEDDING_NPC + 1;
export const MODEL_NPC_QUARREL = MODEL_NPC_DEVIN + 1;
export const MODEL_NPC_CASTEL_GATE = MODEL_NPC_QUARREL + 1;
export const MODEL_CURSEDTEMPLE_ENTER_NPC = MODEL_NPC_CASTEL_GATE + 1;
export const MODEL_CURSEDTEMPLE_ALLIED_NPC = MODEL_CURSEDTEMPLE_ENTER_NPC + 1;
export const MODEL_CURSEDTEMPLE_ILLUSION_NPC =
  MODEL_CURSEDTEMPLE_ALLIED_NPC + 1;
export const MODEL_CURSEDTEMPLE_STATUE = MODEL_CURSEDTEMPLE_ILLUSION_NPC + 1;
export const MODEL_CURSEDTEMPLE_ALLIED_BASKET = MODEL_CURSEDTEMPLE_STATUE + 1;
export const MODEL_CURSEDTEMPLE_ILLUSION__BASKET =
  MODEL_CURSEDTEMPLE_ALLIED_BASKET + 1;
export const MODEL_ELBELAND_SILVIA = MODEL_CURSEDTEMPLE_ILLUSION__BASKET + 1;
export const MODEL_ELBELAND_RHEA = MODEL_ELBELAND_SILVIA + 1;
export const MODEL_ELBELAND_MARCE = MODEL_ELBELAND_RHEA + 1;
export const MODEL_NPC_CHERRYBLOSSOM = MODEL_ELBELAND_MARCE + 1;
export const MODEL_NPC_CHERRYBLOSSOMTREE = MODEL_NPC_CHERRYBLOSSOM + 1;
export const MODEL_SEED_MASTER = MODEL_NPC_CHERRYBLOSSOMTREE + 1;
export const MODEL_SEED_INVESTIGATOR = MODEL_SEED_MASTER + 1;
export const MODEL_LITTLESANTA = MODEL_SEED_INVESTIGATOR + 1;
export const MODEL_XMAS2008_SNOWMAN = MODEL_LITTLESANTA + 1;
export const MODEL_XMAS2008_SNOWMAN_HEAD = MODEL_XMAS2008_SNOWMAN + 1;
export const MODEL_XMAS2008_SNOWMAN_BODY = MODEL_XMAS2008_SNOWMAN_HEAD + 1;
export const MODEL_XMAS2008_SNOWMAN_NPC = MODEL_XMAS2008_SNOWMAN_BODY + 1;
export const MODEL_XMAS2008_SANTA_NPC = MODEL_XMAS2008_SNOWMAN_NPC + 1;
export const MODEL_DUEL_NPC_TITUS = MODEL_XMAS2008_SANTA_NPC + 1;
export const MODEL_GAMBLE_NPC_MOSS = MODEL_DUEL_NPC_TITUS + 1;
export const MODEL_DOPPELGANGER_NPC_LUGARD = MODEL_GAMBLE_NPC_MOSS + 1;
export const MODEL_DOPPELGANGER_NPC_BOX = MODEL_DOPPELGANGER_NPC_LUGARD + 1;
export const MODEL_DOPPELGANGER_NPC_GOLDENBOX = MODEL_DOPPELGANGER_NPC_BOX + 1;
export const MODAL_GENS_NPC_DUPRIAN = MODEL_DOPPELGANGER_NPC_GOLDENBOX + 1;
export const MODAL_GENS_NPC_BARNERT = MODAL_GENS_NPC_DUPRIAN + 1;
export const MODEL_UNITEDMARKETPLACE_CHRISTIN = MODAL_GENS_NPC_BARNERT + 1;
export const MODEL_UNITEDMARKETPLACE_RAUL =
  MODEL_UNITEDMARKETPLACE_CHRISTIN + 1;
export const MODEL_UNITEDMARKETPLACE_JULIA = MODEL_UNITEDMARKETPLACE_RAUL + 1;
export const MODEL_NPC_END = MODEL_UNITEDMARKETPLACE_JULIA + 1;
export const MODEL_PLAYER = MODEL_NPC_END + 1;

export enum PlayerAction {
  PLAYER_SET,
  PLAYER_STOP_MALE,
  PLAYER_STOP_FEMALE,
  PLAYER_STOP_SUMMONER,
  PLAYER_STOP_SWORD,
  PLAYER_STOP_TWO_HAND_SWORD,
  PLAYER_STOP_SPEAR,
  PLAYER_STOP_SCYTHE,
  PLAYER_STOP_BOW,
  PLAYER_STOP_CROSSBOW,
  PLAYER_STOP_WAND,
  PLAYER_STOP_FLY,
  PLAYER_STOP_FLY_CROSSBOW,
  PLAYER_STOP_RIDE,
  PLAYER_STOP_RIDE_WEAPON,
  PLAYER_WALK_MALE,
  PLAYER_WALK_FEMALE,
  PLAYER_WALK_SWORD,
  PLAYER_WALK_TWO_HAND_SWORD,
  PLAYER_WALK_SPEAR,
  PLAYER_WALK_SCYTHE,
  PLAYER_WALK_BOW,
  PLAYER_WALK_CROSSBOW,
  PLAYER_WALK_WAND,
  PLAYER_WALK_SWIM,
  PLAYER_RUN,
  PLAYER_RUN_SWORD,
  PLAYER_RUN_TWO_SWORD,
  PLAYER_RUN_TWO_HAND_SWORD,
  PLAYER_RUN_SPEAR,
  PLAYER_RUN_BOW,
  PLAYER_RUN_CROSSBOW,
  PLAYER_RUN_WAND,
  PLAYER_RUN_SWIM,
  PLAYER_FLY,
  PLAYER_FLY_CROSSBOW,
  PLAYER_RUN_RIDE,
  PLAYER_RUN_RIDE_WEAPON,
  PLAYER_ATTACK_FIST,
  PLAYER_ATTACK_SWORD_RIGHT1,
  PLAYER_ATTACK_SWORD_RIGHT2,
  PLAYER_ATTACK_SWORD_LEFT1,
  PLAYER_ATTACK_SWORD_LEFT2,
  PLAYER_ATTACK_TWO_HAND_SWORD1,
  PLAYER_ATTACK_TWO_HAND_SWORD2,
  PLAYER_ATTACK_TWO_HAND_SWORD3,
  PLAYER_ATTACK_SPEAR1,
  PLAYER_ATTACK_SCYTHE1,
  PLAYER_ATTACK_SCYTHE2,
  PLAYER_ATTACK_SCYTHE3,
  PLAYER_ATTACK_BOW,
  PLAYER_ATTACK_CROSSBOW,
  PLAYER_ATTACK_FLY_BOW,
  PLAYER_ATTACK_FLY_CROSSBOW,
  PLAYER_ATTACK_RIDE_SWORD,
  PLAYER_ATTACK_RIDE_TWO_HAND_SWORD,
  PLAYER_ATTACK_RIDE_SPEAR,
  PLAYER_ATTACK_RIDE_SCYTHE,
  PLAYER_ATTACK_RIDE_BOW,
  PLAYER_ATTACK_RIDE_CROSSBOW,
  PLAYER_ATTACK_SKILL_SWORD1,
  PLAYER_ATTACK_SKILL_SWORD2,
  PLAYER_ATTACK_SKILL_SWORD3,
  PLAYER_ATTACK_SKILL_SWORD4,
  PLAYER_ATTACK_SKILL_SWORD5,
  PLAYER_ATTACK_SKILL_WHEEL,
  PLAYER_ATTACK_SKILL_FURY_STRIKE,
  PLAYER_SKILL_VITALITY,
  PLAYER_SKILL_RIDER,
  PLAYER_SKILL_RIDER_FLY,
  PLAYER_ATTACK_SKILL_SPEAR,
  PLAYER_ATTACK_ONETOONE,
  PLAYER_SKILL_HELL_BEGIN,
  PLAYER_SKILL_HELL_START,
  PLAYER_ATTACK_END,
  PLAYER_FLY_RIDE = PLAYER_ATTACK_END,
  PLAYER_FLY_RIDE_WEAPON,
  PLAYER_DARKLORD_STAND,
  PLAYER_DARKLORD_WALK,
  PLAYER_STOP_RIDE_HORSE,
  PLAYER_RUN_RIDE_HORSE,
  PLAYER_ATTACK_STRIKE,
  PLAYER_ATTACK_TELEPORT,
  PLAYER_ATTACK_RIDE_STRIKE,
  PLAYER_ATTACK_RIDE_TELEPORT,
  PLAYER_ATTACK_RIDE_HORSE_SWORD,
  PLAYER_ATTACK_RIDE_ATTACK_FLASH,
  PLAYER_ATTACK_RIDE_ATTACK_MAGIC,
  PLAYER_ATTACK_DARKHORSE,
  PLAYER_IDLE1_DARKHORSE,
  PLAYER_IDLE2_DARKHORSE,
  PLAYER_FENRIR_ATTACK,
  PLAYER_FENRIR_ATTACK_DARKLORD_AQUA,
  PLAYER_FENRIR_ATTACK_DARKLORD_STRIKE,
  PLAYER_FENRIR_ATTACK_DARKLORD_SWORD,
  PLAYER_FENRIR_ATTACK_DARKLORD_TELEPORT,
  PLAYER_FENRIR_ATTACK_DARKLORD_FLASH,
  PLAYER_FENRIR_ATTACK_TWO_SWORD,
  PLAYER_FENRIR_ATTACK_MAGIC,
  PLAYER_FENRIR_ATTACK_CROSSBOW,
  PLAYER_FENRIR_ATTACK_SPEAR,
  PLAYER_FENRIR_ATTACK_ONE_SWORD,
  PLAYER_FENRIR_ATTACK_BOW,
  PLAYER_FENRIR_SKILL,
  PLAYER_FENRIR_SKILL_TWO_SWORD,
  PLAYER_FENRIR_SKILL_ONE_RIGHT,
  PLAYER_FENRIR_SKILL_ONE_LEFT,
  PLAYER_FENRIR_DAMAGE,
  PLAYER_FENRIR_DAMAGE_TWO_SWORD,
  PLAYER_FENRIR_DAMAGE_ONE_RIGHT,
  PLAYER_FENRIR_DAMAGE_ONE_LEFT,
  PLAYER_FENRIR_RUN,
  PLAYER_FENRIR_RUN_TWO_SWORD,
  PLAYER_FENRIR_RUN_ONE_RIGHT,
  PLAYER_FENRIR_RUN_ONE_LEFT,
  PLAYER_FENRIR_RUN_MAGOM,
  PLAYER_FENRIR_RUN_TWO_SWORD_MAGOM,
  PLAYER_FENRIR_RUN_ONE_RIGHT_MAGOM,
  PLAYER_FENRIR_RUN_ONE_LEFT_MAGOM,
  PLAYER_FENRIR_RUN_ELF,
  PLAYER_FENRIR_RUN_TWO_SWORD_ELF,
  PLAYER_FENRIR_RUN_ONE_RIGHT_ELF,
  PLAYER_FENRIR_RUN_ONE_LEFT_ELF,
  PLAYER_FENRIR_STAND,
  PLAYER_FENRIR_STAND_TWO_SWORD,
  PLAYER_FENRIR_STAND_ONE_RIGHT,
  PLAYER_FENRIR_STAND_ONE_LEFT,
  PLAYER_FENRIR_WALK,
  PLAYER_FENRIR_WALK_TWO_SWORD,
  PLAYER_FENRIR_WALK_ONE_RIGHT,
  PLAYER_FENRIR_WALK_ONE_LEFT,
  PLAYER_ATTACK_BOW_UP,
  PLAYER_ATTACK_CROSSBOW_UP,
  PLAYER_ATTACK_FLY_BOW_UP,
  PLAYER_ATTACK_FLY_CROSSBOW_UP,
  PLAYER_ATTACK_RIDE_BOW_UP,
  PLAYER_ATTACK_RIDE_CROSSBOW_UP,
  PLAYER_ATTACK_ONE_FLASH,
  PLAYER_ATTACK_RUSH,
  PLAYER_ATTACK_DEATH_CANNON,
  PLAYER_ATTACK_REMOVAL,
  PLAYER_ATTACK_STUN,
  PLAYER_HIGH_SHOCK,
  PLAYER_STOP_TWO_HAND_SWORD_TWO,
  PLAYER_WALK_TWO_HAND_SWORD_TWO,
  PLAYER_RUN_TWO_HAND_SWORD_TWO,
  PLAYER_ATTACK_TWO_HAND_SWORD_TWO,
  PLAYER_SKILL_HAND1,
  PLAYER_SKILL_HAND2,
  PLAYER_SKILL_WEAPON1,
  PLAYER_SKILL_WEAPON2,
  PLAYER_SKILL_ELF1,
  PLAYER_SKILL_TELEPORT,
  PLAYER_SKILL_FLASH,
  PLAYER_SKILL_INFERNO,
  PLAYER_SKILL_HELL,
  PLAYER_RIDE_SKILL,
  PLAYER_SKILL_SLEEP,
  PLAYER_SKILL_SLEEP_UNI,
  PLAYER_SKILL_SLEEP_DINO,
  PLAYER_SKILL_SLEEP_FENRIR,
  PLAYER_SKILL_CHAIN_LIGHTNING,
  PLAYER_SKILL_CHAIN_LIGHTNING_UNI,
  PLAYER_SKILL_CHAIN_LIGHTNING_DINO,
  PLAYER_SKILL_CHAIN_LIGHTNING_FENRIR,
  PLAYER_SKILL_LIGHTNING_ORB,
  PLAYER_SKILL_LIGHTNING_ORB_UNI,
  PLAYER_SKILL_LIGHTNING_ORB_DINO,
  PLAYER_SKILL_LIGHTNING_ORB_FENRIR,
  PLAYER_SKILL_DRAIN_LIFE,
  PLAYER_SKILL_DRAIN_LIFE_UNI,
  PLAYER_SKILL_DRAIN_LIFE_DINO,
  PLAYER_SKILL_DRAIN_LIFE_FENRIR,
  PLAYER_SKILL_SUMMON,
  PLAYER_SKILL_SUMMON_UNI,
  PLAYER_SKILL_SUMMON_DINO,
  PLAYER_SKILL_SUMMON_FENRIR,
  PLAYER_SKILL_BLOW_OF_DESTRUCTION,
  PLAYER_SKILL_SWELL_OF_MP,
  PLAYER_SKILL_MULTISHOT_BOW_STAND,
  PLAYER_SKILL_MULTISHOT_BOW_FLYING,
  PLAYER_SKILL_MULTISHOT_CROSSBOW_STAND,
  PLAYER_SKILL_MULTISHOT_CROSSBOW_FLYING,
  PLAYER_SKILL_RECOVERY,
  PLAYER_SKILL_GIGANTICSTORM,
  PLAYER_SKILL_FLAMESTRIKE,
  PLAYER_SKILL_LIGHTNING_SHOCK,
  // #ifdef YDG_ADD_SKILL_RIDING_ANIMATIONS
  //     PLAYER_SKILL_GIGANTICSTORM_UNI,
  //     PLAYER_SKILL_GIGANTICSTORM_DINO,
  //     PLAYER_SKILL_GIGANTICSTORM_FENRIR,
  //     PLAYER_ATTACK_SKILL_WHEEL_UNI,
  //     PLAYER_ATTACK_SKILL_WHEEL_DINO,
  //     PLAYER_ATTACK_SKILL_WHEEL_FENRIR,
  // #endif
  PLAYER_DEFENSE1,
  PLAYER_GREETING1,
  PLAYER_GREETING_FEMALE1,
  PLAYER_GOODBYE1,
  PLAYER_GOODBYE_FEMALE1,
  PLAYER_CLAP1,
  PLAYER_CLAP_FEMALE1,
  PLAYER_CHEER1,
  PLAYER_CHEER_FEMALE1,
  PLAYER_DIRECTION1,
  PLAYER_DIRECTION_FEMALE1,
  PLAYER_GESTURE1,
  PLAYER_GESTURE_FEMALE1,
  PLAYER_UNKNOWN1,
  PLAYER_UNKNOWN_FEMALE1,
  PLAYER_CRY1,
  PLAYER_CRY_FEMALE1,
  PLAYER_AWKWARD1,
  PLAYER_AWKWARD_FEMALE1,
  PLAYER_SEE1,
  PLAYER_SEE_FEMALE1,
  PLAYER_WIN1,
  PLAYER_WIN_FEMALE1,
  PLAYER_SMILE1,
  PLAYER_SMILE_FEMALE1,
  PLAYER_SLEEP1,
  PLAYER_SLEEP_FEMALE1,
  PLAYER_COLD1,
  PLAYER_COLD_FEMALE1,
  PLAYER_AGAIN1,
  PLAYER_AGAIN_FEMALE1,
  PLAYER_RESPECT1,
  PLAYER_SALUTE1,
  PLAYER_SCISSORS,
  PLAYER_ROCK,
  PLAYER_PAPER,
  PLAYER_HUSTLE,
  PLAYER_PROVOCATION,
  PLAYER_LOOK_AROUND,
  PLAYER_CHEERS,
  PLAYER_KOREA_HANDCLAP,
  PLAYER_POINT_DANCE,
  PLAYER_RUSH1,
  PLAYER_COME_UP,
  PLAYER_SHOCK,
  PLAYER_DIE1,
  PLAYER_DIE2,
  PLAYER_SIT1,
  PLAYER_SIT2,
  PLAYER_SIT_FEMALE1,
  PLAYER_SIT_FEMALE2,
  PLAYER_HEALING1,
  PLAYER_HEALING_FEMALE1,
  PLAYER_POSE1,
  PLAYER_POSE_FEMALE1,
  PLAYER_JACK_1,
  PLAYER_JACK_2,
  PLAYER_SANTA_1,
  PLAYER_SANTA_2,
  PLAYER_CHANGE_UP,
  PLAYER_RECOVER_SKILL,
  PLAYER_SKILL_THRUST,
  PLAYER_SKILL_STAMP,
  PLAYER_SKILL_GIANTSWING,
  PLAYER_SKILL_DARKSIDE_READY,
  PLAYER_SKILL_DARKSIDE_ATTACK,
  PLAYER_SKILL_DRAGONKICK,
  PLAYER_SKILL_DRAGONLORE,
  PLAYER_SKILL_PHOENIX_SHOT,
  PLAYER_SKILL_ATT_UP_OURFORCES,
  PLAYER_SKILL_HP_UP_OURFORCES,
  // ������ ������ ���� �ִ�
  PLAYER_RAGE_UNI_ATTACK,
  PLAYER_RAGE_UNI_ATTACK_ONE_RIGHT,
  PLAYER_RAGE_UNI_RUN,
  PLAYER_RAGE_UNI_RUN_ONE_RIGHT,
  PLAYER_RAGE_UNI_STOP_ONE_RIGHT,
  PLAYER_RAGE_FENRIR,
  PLAYER_RAGE_FENRIR_TWO_SWORD,
  PLAYER_RAGE_FENRIR_ONE_RIGHT,
  PLAYER_RAGE_FENRIR_ONE_LEFT,
  PLAYER_RAGE_FENRIR_WALK,
  PLAYER_RAGE_FENRIR_WALK_ONE_RIGHT,
  PLAYER_RAGE_FENRIR_WALK_ONE_LEFT,
  PLAYER_RAGE_FENRIR_WALK_TWO_SWORD,
  PLAYER_RAGE_FENRIR_RUN,
  PLAYER_RAGE_FENRIR_RUN_TWO_SWORD,
  PLAYER_RAGE_FENRIR_RUN_ONE_RIGHT,
  PLAYER_RAGE_FENRIR_RUN_ONE_LEFT,
  PLAYER_RAGE_FENRIR_STAND,
  PLAYER_RAGE_FENRIR_STAND_TWO_SWORD,
  PLAYER_RAGE_FENRIR_STAND_ONE_RIGHT,
  PLAYER_RAGE_FENRIR_STAND_ONE_LEFT,
  PLAYER_RAGE_FENRIR_DAMAGE,
  PLAYER_RAGE_FENRIR_DAMAGE_TWO_SWORD,
  PLAYER_RAGE_FENRIR_DAMAGE_ONE_RIGHT,
  PLAYER_RAGE_FENRIR_DAMAGE_ONE_LEFT,
  PLAYER_RAGE_FENRIR_ATTACK_RIGHT,
  PLAYER_STOP_RAGEFIGHTER,
  MAX_PLAYER_ACTION,
}

export enum MovementMode {
  Walk,
  Fly,
  Swim,
}

export enum MonsterActionType {
  Stop1 = 0,
  Stop2 = 1, // Sometimes used as an alternate idle animation or reaction
  Walk = 2,
  Attack1 = 3,
  Attack2 = 4,
  Shock = 5, // Taking damage
  Die = 6,
  Appear = 7, // Appearing (e.g., for bosses)
  Attack3 = 8,
  Attack4 = 9,
  Run = 10, // If the monster has a separate run animation
}

export enum ServerPlayerActionType {
  Attack1 = 120, // AT_ATTACK1
  Attack2 = 121, // AT_ATTACK2

  Stand1 = 122, // AT_STAND1
  Stand2 = 123, // AT_STAND2
  Move1 = 124, // AT_MOVE1
  Move2 = 125, // AT_MOVE2
  Damage1 = 126, // AT_DAMAGE1
  Die1 = 127, // AT_DIE1

  // *** DOTYCHCZASOWE WPISY – NIE ZMIENIAMY KOLEJNOŚCI ***
  Sit = 128, // AT_SIT1
  Pose = 129, // AT_POSE1
  Healing = 130, // AT_HEALING1

  Greeting = 131, // AT_GREETING1
  Goodbye = 132, // AT_GOODBYE1
  Clap = 133, // AT_CLAP1
  Gesture = 134, // AT_GESTURE1
  Direction = 135, // AT_DIRECTION1
  Unknown = 136, // AT_UNKNOWN1
  Cry = 137, // AT_CRY1
  Cheer = 138, // AT_CHEER1
  Awkward = 139, // AT_AWKWARD1
  See = 140, // AT_SEE1
  Win = 141, // AT_WIN1
  Smile = 142, // AT_SMILE1
  Sleep = 143, // AT_SLEEP1
  Cold = 144, // AT_COLD1
  Again = 145, // AT_AGAIN1
  Respect = 146, // AT_RESPECT1
  Salute = 147, // AT_SALUTE1
  Rush = 148, // AT_RUSH1
  Scissors = 149, // AT_SCISSORS
  Rock = 150, // AT_ROCK
  Paper = 151, // AT_PAPER
  Hustle = 152, // AT_HUSTLE
  Provocation = 153, // AT_PROVOCATION
  LookAround = 154, // AT_LOOK_AROUND
  Cheers = 155, // AT_CHEERS

  Jack1 = 156, // AT_JACK1
  Jack2 = 157, // AT_JACK2
  Santa1_1 = 158, // AT_SANTA1_1
  Santa1_2 = 159, // AT_SANTA1_2
  Santa1_3 = 160, // AT_SANTA1_3
  Santa2_1 = 161, // AT_SANTA2_1
  Santa2_2 = 162, // AT_SANTA2_2
  Santa2_3 = 163, // AT_SANTA2_3
}

export enum BlendState {
  ALPHA_DISABLE,
  ALPHA_ADD,
  ALPHA_COMBINE,
  ALPHA_SUBTRCT,
  ALPHA_MULTIPY,
  ALPHA_MAXIMIED,
  ALPHA_ONEOE,
  ALPHA_PREMLTIPLIED,
  ALPHA_PREMULTIPLID_PORTERDUFF,
  ALPHA_INTERPOLAE,
  ALPHA_SCREENMOE,
}

export const ItemGroups = {
  Boots: 11,
  Gloves: 10,
  Pants: 9,
  Helm: 7,
  Armor: 8,
} as const;
